apiVersion: v1
kind: ServiceAccount
metadata:
  name: aether
  namespace: aether
  labels:
    app.kubernetes.io/name: aether
    app.kubernetes.io/component: server
automountServiceAccountToken: false
