{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aether.fullname" . }}-postgresql
  labels:
    {{- include "aether.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=require" .Values.postgresql.auth.username .Values.postgresql.auth.password (printf "%s-postgresql" (include "aether.fullname" .)) (.Values.postgresql.external.port | default 5432 | int) .Values.postgresql.auth.database | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.security.jwtSecret (not .Values.security.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aether.fullname" . }}-jwt
  labels:
    {{- include "aether.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.security.jwtSecret | b64enc | quote }}
{{- end }}
